version: "3.1"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: waterdip-server
    image: waterdip-server
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/.venv
    restart: "unless-stopped"

volumes:
  data:
    driver: local
